# Generated by Django 3.0.2 on 2020-06-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(auto_now=True, verbose_name='Дата публикауции'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='pub_date',
            field=models.DateField(auto_now=True, verbose_name='Дата публикауции'),
        ),
    ]
