# Generated by Django 3.0.2 on 2020-06-01 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200601_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикауции'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикауции'),
        ),
    ]
