# Generated by Django 3.0.2 on 2020-06-08 18:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200601_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='txt',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
