# Generated by Django 3.0.2 on 2020-06-10 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20200608_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='second_author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='third_author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='written',
            field=models.ManyToManyField(blank=True, related_name='authors', to='home.Book'),
        ),
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
