# Generated by Django 3.0.2 on 2020-06-08 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0007_auto_20200608_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='author',
        ),
        migrations.RemoveField(
            model_name='test',
            name='title',
        ),
    ]
